### ISSUE TITLE
Feature : errors flagged in case of incorrect symbol

### ISSUE THREAD

**Issue by dawadam** [endenwer/tradingview-ws#1]
Hello, thank you for the work and share.
It would be handy to have errors flagged in case of incorrect symbol.

```
        const connection = await connect()
        const candles = await getCandles({
            connection,
            symbols: ['FX:AUDCAD', 'TEST:FAIL', 'FX:AUDCHF'],
            amount: 10,
            timeframe: 60
        })
        await connection.close()
        console.log(`Candles for AUDCAD:`, candles[0])
        console.log(`Candles for FAIL:`, candles[1])
        console.log(`Candles for AUDCHF:`, candles[2])
```

Currently no response, __getCandles__ function does not complete.

**Comment by endenwer** [comment]
Hello, thanks for the report. I released new version. Now `getCandles` returns empty candles for incorrect symbols. There is no errors returned for now, but I plan to change the interface for something like this  `const [candles, errors] = await getCandles(...)` or maybe add `onError` callback. If that solves you problem, you can close the issue.
