### ISSUE TITLE
Subscribing to connection with multiple symbol

### ISSUE THREAD

**Issue by catlowlevel** [endenwer/tradingview-ws#2]
Subscribing to connection with multiple symbol, all the symbol information is only received once, after that only the last symbol in symbols array is received.

i found this out after trying to watch for multiple symbol price

```
connection.subscribe((ev) => {
		switch (ev.name) {
			case "series_loading": {
				if (ev.params.length != 3) break;
				currentData.type = ev.params[2];
				break;
			}
			case "symbol_resolved": {
				symbolResolved = true;
				currentData.symbol = ev.params[2].base_currency;
				break;
			}
			case "timescale_update": {
				if (!symbolResolved) break;
				const param = ev.params[1];
				const sds = param.sds_1;
				const s = sds.s;
				const close = s[0].v[4];
				currentData.price = close;
				break;
			}

			case "series_completed": {
				if (!symbolResolved) break;
				symbolResolved = false;
				console.log(`${currentData.symbol} is now at ${currentData.price}`);
				data.push(currentData);
				break;
			}
			case "du": {
				if (data.length === 0) break;
				const params = ev.params[1];
				const sds = params.sds_1;
				const t = sds.t;
				const s = data.find(d => d.type === t);
				if(s){
					console.log(`${s.symbol} is now at ${s.price}`);
				}
				break;
			}
			default:
				break;
		}
```

the case with "du" only receive the last symbol in the symbols array.

Thanks.

**Comment by endenwer** [comment]
I think it is a limitation of free plan. You can open only one chart at a time. But if you want realtime prices for multiple symbols you can subscribe for watchlist. I don't remember the even name and the data they send, but I saw that subscription when I was developing the library.

**Comment by reizhafajrian** [comment]
I just found a solution, but this one is temporary I just using this for 2 symbols,haven't try more than 2


```
    for (const iterator of ["BTCUSDT","SOLUSDT"]) {
      const connection = await connect()
      await getCandles({
        connection,
        symbols: [iterator],
        amount: 1,
        timeframe: 1
      })
      connection.subscribe(event => {
        console.log(event.params[1]['sds_1']?.s, "payload")
      })
    }
```

**Comment by reizhafajrian** [comment]
> I think it is a limitation of free plan. You can open only one chart at a time. But if you want realtime prices for multiple symbols you can subscribe for watchlist. I don't remember the even name and the data they send, but I saw that subscription when I was developing the library.
where can i see the event type?

**Comment by reizhafajrian** [comment]
> I think it is a limitation of free plan. You can open only one chart at a time. But if you want realtime prices for multiple symbols you can subscribe for watchlist. I don't remember the even name and the data they send, but I saw that subscription when I was developing the library.

where can i see the event type?i mean maybe i can help to develop new feature

**Comment by endenwer** [comment]
> where can i see the event type?

it is `event.name`.
